### ISSUE TITLE
Failed to build jSite

### ISSUE THREAD

**Issue by marek22k** [Bombe/jSite#6]
Hello,

compiling jSite does not work.

```
$./gradlew

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '17.0.7'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```
[Full log](https://github.com/Bombe/jSite/files/12898327/session.txt)

**Comment by Bombe** [comment]
Haha, oh wow, I guess the bundled Gradle version is simply too old… 😄

**Comment by Bombe** [comment]
Yeah, can replicate that with 17.0.8 locally… Java 11 is also too new but Java 8 will work. I should _really_ look into that…

**Comment by Bombe** [comment]
Okay, pushed some changes to [`next`](https://github.com/Bombe/jSite/tree/next), compiles with Java 8, 11, 17, and 21, and the tests run, too! 🙂
